---
on: [push, pull_request]
name: Stylua

jobs:

  stylua:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-versions: ["stable", "nightly"]
    name: Stylua
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
